service: serverless-contact-mailer #gcf-nodejs # NOTE: Don't put the word "google" in here

provider:
  name: google
  stage: dev
  timeout: 60s
  runtime: nodejs8
  region: us-central1
  project: serverless-mailer
  credentials: C:\Users\L000-MP1C8A4G\gcloud\keyfile.json #~/.gcloud/keyfile.json # the path to the credentials file needs to be absolute

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - yarn.lock
    - README.md
    - data.json
    - index.js

functions:
  contact:
    handler: contact #handler.contact
    timeout: 60s
    memorySize: 256
    events:
      - http:
          cors: true
          method: POST
          path: contact
    environment:
      CONTACT_ADDRESS: #
      EMAIL_ADDRESS: #
      EMAIL_PASSWORD: #